### PR TITLE
Decouple symfony

### PR DESCRIPTION
**Pull request by davedevelopment**
A start on #22, at least this way people can use the basics without pulling down all of symfony

### CODE REVIEW

**Comment by cainmi** [comment]
Any movement on this?

**Comment by michaeljs1990** [comment]
This should really be merged in. It's a huge pain to have to install symfony when you don't even need it making dependency graphs a huge pain in the ass.

**Comment by richsage** [comment]
I'd really like to separate this out into a library and bundle ideally - that's why it hasn't been merged in yet. But if you're happy for it to be as-is without Symfony being a dependency then I'll re-look at it.

**Comment by michaeljs1990** [comment]
I would be happy with it as is without symfony. We are using this like a library right now and just autoloading everything and using the classes that we need. I think it would be a good solution in the mean time to drop symfony/symfony while it's being ported into a lib.

**Comment by davedevelopment** [comment]
I've been using it for just over two years like this :)

Rebased if you do want to merge

**Comment by richsage** [comment]
OK that sounds good - thanks all :)

**Comment by michaeljs1990** [comment]
Can we tag this as a 1.6 release?

**Comment by richsage** [comment]
Done - 0.1.6

**Pull request merged**
