### PR TITLE
Configure timeout

### LINKED ISSUE #80: Sending to Android GCM not working when timeout greather than 5 sec
I have a problem when trying to send push to android by gcm. Problem resolve when i set timeout 15 or 30 sec in /vendor/kriswallsmith/buzz/lib/Buzz/Client/AbstractClient.php

### PR DESCRIPTION
**Pull request by richsage**
Fixes #80. Defaults are as before - 5 seconds for Android, Blackberry and Windows (since they use the Buzz client), and 60.

ping @andrewsmm @emiliomg - could you both test and see if this helps you?

### CODE REVIEW

**Comment by emiliomg** [comment]
Thank you. I will review this PR in the evening :-)

**Comment by emiliomg** [comment]
The PR does not work yet, you did not set the necessary "rms_push_notifications.INSERT_PLATFORM_HERE.timeout" parameter in RMSPushNotificationsExtension.php, so the DI cannot resolve the requested parameter key.

**Comment by richsage** [comment]
Ah yeah, that'll teach me to try and do it quickly :-) I've added it now, could you check?

**Comment by emiliomg** [comment]
Thank you. Yes, I will check it out as soon as I can.

**Comment by emiliomg** [comment]
Works fine with android. Didn't test the rest ;-)

**Comment by snjegov** [comment]
i raised the limit to 120 (for iOS) but it still timeouts. maybe my problem is somewhere else, but where? sometimes notifications pass, sometimes they don't :/

**Comment by emiliomg** [comment]
So, can this branch be merged? :)

**Comment by snjegov** [comment]
Sure thing.

**Pull request merged**
